name: Build Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
          
      - name: Build
        run: dotnet build SnsAndroidFix.csproj
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: SnsAndroidFix
          path: bin/Debug/net9.0/SnsAndroidFix.dll
